### ISSUE TITLE
CONNECT-UDP and multiple intermediaries

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/masque-drafts#21]
> Note that when multiple proxies are involved in a CONNECT-UDP request, all the HTTP connections along the path need to be using HTTP/3 [H3] or later in order for UDP payloads to be sent over QUIC DATAGRAM frames.

How is this true?  The first proxy should convert the stream of encapsulated UDP datagrams into actual UDP datagrams.  That means that the second proxy won't see these as part of the connection.

This is only an issue if the proxy wants to pass the DATAGRAM frames on to the next proxy.  But that's not what is being asked of it, if it does that, it does so on its own recognizance.  (I should add: if it chooses to forward to a next hop that uses h2, then it can take the DATAGRAM frames and stuff them into the request stream.)

**Comment by DavidSchinazi** [comment]
It's definitely possible for a chain of proxies to use heterogeneous encodings for their UDP packets, by which I mean if the topology is `Client - ProxyA - ProxyB - Destination` then we could build this so that `Client - ProxyA` uses DATAGRAM frames whereas `ProxyA - ProxyB` uses the stream encoding with HTTP/2.

I don't think the benefits outweigh the added complexity, so the current design is all-or-nothing: if all legs supports H3-DATAGRAM then it can be used, otherwise fallback to the stream encoding.

**Comment by martinthomson** [comment]
I'm not really clear on how you think that might work.  If Client and Proxy A negotiate the use of DATAGRAM, does this depend on Proxy A verifying first that Proxy B also supports DATAGRAM?  How do you ensure that the identifiers are comprehensible to all parties?

**Comment by DavidSchinazi** [comment]
This issue has been moved to the [WG repo](https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/issues/1)
